### ISSUE TITLE
Vue Routerlink Underscore

### ISSUE THREAD

**Issue by woq** [woq/sango#2]
how to fix it?

**Comment by woq** [comment]
```css
a {
    text-decoration: none;
  }
 
.router-link-active {
    text-decoration: none;
  }
```
